comment_width = 120
group_imports = "StdExternalCrate"
imports_granularity = "Module"
max_width = 120
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
tab_spaces = 4
version = "Two"
wrap_comments = true
