name = "redirekt"
type = "webpack"
zone_id = "**redacted**"
account_id = "**redacted**"
routes = ["example.com/*"]
workers_dot_dev = false
webpack_config = "webpack.config.js"
vars = { BASE_URL = "https://example.com/" }
