name: Build

on:
  push:
    branches:
      - renovate/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build
        shell: bash
        run: |
          npm install
          npm install -D webpack-cli
          npm run build
