name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build
        shell: bash
        run: |
          npm install
          npm install -D webpack-cli
          npm run build
